"""Add report parameters tables

Revision ID: 3eeae99da945
Revises: 007
Create Date: 2025-09-28 08:03:04.844561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eeae99da945'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'auto_execute_query',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_conversations_db_alias'), 'conversations', ['db_alias'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_db_alias'), table_name='conversations')
    op.alter_column('conversations', 'auto_execute_query',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    # ### end Alembic commands ###