"""Fix report parameters UUID fields

Revision ID: 7407468662e5
Revises: 3eeae99da945
Create Date: 2025-09-28 08:08:36.766903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7407468662e5'
down_revision = '3eeae99da945'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###